lms/urls.py
# Core Django imports.
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include

# LMS app imports
from lms.views.account.login_view import UserLoginView
from lms.views.account.logout_view import UserLogoutView
from lms.views.account.register_view import (
    ActivateView,
    AccountActivationSentView,
    UserRegisterView,
)
from lms.views.account.subscriber_view import subscribe, subscribe_confirm, subscribe_delete, sub_delete
from lms.views.assignment.assignment_views import (
    AssignmentHomeView,
    AssignmentDetailView,
    AssignmentCreateView,
    AssignmentUpdateView,
    AssignmentDeleteView,
    CommentCreateView, AssignmentHomeStudentView, AssignmentDetailStudentView,
)
from lms.views.blog.blog_view import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from lms.views.course.course_publish_views import (
    CoursePublishView,
    CourseUnPublishView
)
from lms.views.course.course_registration_views import (
    CourseRegistrationView,
)
from lms.views.course.course_views import (
    CourseListView,
    GradeBookCourseView,
    StudentGradeBookCourseView, CourseCreateView
    # table_download
)
from lms.views.course.grading_scheme_view import (
    GradingSchemeUpdateView,
    GradingSchemeCreateView
)
from lms.views.course.group_creation_view import (
    GroupCreationRequestView,
    GroupCreationRequestSentView,
    ViewGroupsView
)
from lms.views.course.mail_to_admin_view import (
    MailToAdminView

)
from lms.views.course.settings_view import (
    CourseDetailsView,
    CourseManageView,
    CourseSectionsView,
    CourseStatisticsView
)
from lms.views.dashboard.dashboard_views import (
    DashboardHomeView,
    DashboardProfileView,
    dashboard_list,
    dashboard_details,
    dashboard_subscribe
)
from lms.views.notification.notification_settings_view import (
    NotificationSettingsView,
)
from lms.views.quiz.quiz_views import (
    compute_stats,
    fetch_questions_one_at_a_time,
    fetch_questions,
    quiz_home,
    quiz_detail,
    preview_quiz,
    enter_quiz_comment,
    quiz_publish, QuizCreateView, QuizUpdateView, QuizDeleteView,
    QuizQuestionCreateView, QuizQuestionUpdateView, QuizQuestionDeleteView
)

# Specifies the app name for name spacing.
app_name = "lms"

# lms/urls.py
urlpatterns = [

    # LMS URLS #

    # /home/
    path(
        route='course/<int:pk>/',
        view=CourseListView.as_view(),
        name='course-home'
    ),

    # /home/
    path(
        route='course/',
        view=CourseListView.as_view(),
        name='course-home'
    ),

    # Blog URLS #

    # /home/blog
    path(
        route='blog/',
        view=PostListView.as_view(),
        name='blog-home'
    ),

    path(
        route='blog/user/<str:username>/',
        view=UserPostListView.as_view(),
        name='user-posts'
    ),

    path(
        route='blog/post/<int:pk>/',
        view=PostDetailView.as_view(),
        name='post-detail'
    ),

    path(
        route='blog/post/new/',
        view=PostCreateView.as_view(),
        name='post-create'
    ),

    path(
        route='blog/post/<int:pk>/update/',
        view=PostUpdateView.as_view(),
        name='post-update'
    ),

    path(
        route='blog/post/<int:pk>/delete/',
        view=PostDeleteView.as_view(),
        name='post-delete'
    ),

    # ACCOUNT URLS #

    # /account/login/
    path(
        route='account/login/',
        view=UserLoginView.as_view(),
        name='login'
    ),

    # /account/login/
    path(
        route='account/register/',
        view=UserRegisterView.as_view(),
        name='register'
    ),

    # /account/logout/
    path(
        route='account/logout/',
        view=UserLogoutView.as_view(),
        name='logout'
    ),

    path(route='account_activation_sent/',
         view=AccountActivationSentView.as_view(),
         name='account_activation_sent'
         ),

    path(route='activate/<uidb64>/<token>/',
         view=ActivateView.as_view(),
         name='activate'
         ),

    # DASHBOARD URLS #

    # /
    path('', dashboard_list, name='home'),
    path('<int:page>', dashboard_list, name='home'),
    path('coursedetails/<int:pk>/', dashboard_details),
    path('subscribe/<int:pk>/', dashboard_subscribe),

    # /author/dashboard/home/
    path(
        route="dashboard/home/",
        view=DashboardHomeView.as_view(),
        name="dashboard_home"
    ),

    # /author/dashboard/profile/
    path(
        route="dashboard/profile/",
        view=DashboardProfileView.as_view(),
        name="dashboard_profile"
    ),

    # /author/course/register
    path(
        route="course/register/<int:pk>/",
        view=CourseRegistrationView.as_view(),
        name="course_register"
    ),

    # /author/course/publish
    path(
        route="course/publish/<int:pk>/",
        view=CoursePublishView.as_view(),
        name="course_publish"
    ),

    # /author/course/unpublish
    path(
        route="course/unpublish/<int:pk>/",
        view=CourseUnPublishView.as_view(),
        name="course_unpublish"
    ),

    path(
        route="course/create/",
        view=CourseCreateView.as_view(),
        name="course_create"
    ),
    # /author/notification/
    path(
        route="notifications/",
        view=NotificationSettingsView.as_view(),
        name="notification_settings"
    ),

    # COURSE SETTINGS URLS #

    path(
        route="course/<int:pk>/details/",
        view=CourseDetailsView.as_view(),
        name="course_details"
    ),
    path(
        route="course/<int:pk>/manage/",
        view=CourseManageView.as_view(),
        name="course_manage"
    ),
    path(
        route="course/<int:pk>/sections/",
        view=CourseSectionsView.as_view(),
        name="course_sections"
    ),
    path(
        route="course/<int:pk>/statistics/",
        view=CourseStatisticsView.as_view(),
        name="course_statistics"
    ),
    path(
        route="course/<int:pk>/grading_scheme/new/",
        view=GradingSchemeCreateView.as_view(),
        name="course_grading_scheme_create"
    ),
    path(
        route="course/<int:pk>/grading_scheme/update/",
        view=GradingSchemeUpdateView.as_view(),
        name="course_grading_scheme_update"
    ),

    # COURSE STUDENT - Group CREATION REQUEST
    path(
        route="course/<int:pk>/group_creation_request/",
        view=GroupCreationRequestView.as_view(),
        name="group_creation_request"
    ),
    path(route='group_request/<int:ck>/<uidb64>/<token>/',
         view=GroupCreationRequestSentView.as_view(),
         name='group_request'
         ),

    # View GROUPS -
    path(
        route="course/<int:pk>/view_groups/",
        view=ViewGroupsView.as_view(),
        name="view_groups"
    ),

    # COURSE STUDENT -  Mail To Admin
    path(
        route="course/<int:pk>/mail_to_admin/",
        view=MailToAdminView.as_view(),
        name="mail_to_admin"
    ),

    # COURSE GRADEBOOK - Teacher's View
    path(
        route="course/<int:course_id>/grades/",
        view=GradeBookCourseView.as_view(),
        name='gradebook-course'
    ),

    path(
        route="course/<int:course_id>/student_grades/",
        view=StudentGradeBookCourseView.as_view(),
        name='gradebook-course-student'
    ),

    # By Quiz Teacher View Team.[Start]
    path('course/<int:course_id>/quiz/course_stats/', compute_stats, name="compute_stats"),

    path('course/<int:course_id>/quiz/<int:pk>/one_at_a_time/', fetch_questions_one_at_a_time,
         name="fetch_questions_one_at_a_time"),

    path('course/<int:course_id>/quiz/<int:pk>/fetch_questions/', fetch_questions, name="fetch_questions"),

    path('course/<int:course_id>/quiz/home/', quiz_home, name="quiz_home"),

    path('course/<int:course_id>/quiz/create/', QuizCreateView.as_view(), name="quiz_create"),
    path('course/<int:course_id>/quiz/<int:pk>/update/', QuizUpdateView.as_view(), name="quiz_update"),
    path('course/<int:course_id>/quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name="quiz_delete"),

    path('course/<int:course_id>/quiz/<int:quiz_id>/question/create', QuizQuestionCreateView.as_view(),
         name="quiz_question_create"),
    path('course/<int:course_id>/quiz/<int:quiz_id>/question/<int:pk>/update/', QuizQuestionUpdateView.as_view(),
         name="quiz_question_update"),
    path('course/<int:course_id>/quiz/<int:quiz_id>/question/<int:pk>/delete/', QuizQuestionDeleteView.as_view(),
         name="quiz_question_delete"),

    path('course/<int:course_id>/quiz/<int:pk>/detail/', quiz_detail, name="quiz_view"),

    path('course/<int:course_id>/quiz/<int:pk>/preview/', preview_quiz, name="preview_quiz"),

    path('course/<int:course_id>/quiz/<int:pk>/enter_quiz_comment/', enter_quiz_comment, name="enter_quiz_comment"),

    path('course/<int:course_id>/quiz/<int:pk>/publish/', quiz_publish, name='quiz_publish'),
    # By Quiz Teacher View Team.[End]

    # Assignment Views
    path(
        route="course/<int:pkcourse>/student_assignment/home/",
        view=AssignmentHomeStudentView.as_view(),
        name="assignment_student_home"
    ),

    path(
        route="course/<int:pkcourse>/student_assignment/home/<int:pk>/",
        view=AssignmentDetailStudentView.as_view(),
        name="assignment_student_detail"
    ),

    path(
        route="course/<int:pkcourse>/assignment/home/",
        view=AssignmentHomeView.as_view(),
        name="assignment_home"
    ),

    path(
        route="course/<int:pkcourse>/assignment/home/<int:pk>/",
        view=AssignmentDetailView.as_view(),
        name="assignment_detail"
    ),

    path(
        route="course/<int:pkcourse>/assignment/create/",
        view=AssignmentCreateView.as_view(),
        name="assignment_create"
    ),
    path(
        route='course/<int:pkcourse>/assignment/<int:pk>/update/',

lmx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls', namespace='lms')),

    # Url for password reset.
    path('account/password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'),
         name='password_reset'),

    # Url for successful password reset.
    path('account/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    # Url for successful password reset confirm.
    path('account/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),

    # Url for password reset done.
    path('account/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # Url for social authentication.
    path('oauth/', include('social_django.urls', namespace="social")),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ]

# if not production add media url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "LMX Admin"
admin.site.site_title = "LMX Admin Portal"
admin.site.index_title = "Welcome to LMX Site Portal"

lms/models/assignment_model.py
# Core Django imports.
import os

from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from image_optimizer.fields import OptimizedImageField

from lms.models.course_model import Course, StudentCourse
from lms.models.user_role_model import Role


def upload_path(instance, filename):
    # change the filename here is required
    return os.path.join(instance.name, filename)


class Assignment(models.Model):
    GRADES_DISPLAY = (
        ('percentage', 'Percentage'),
        ('complete/Incomplete', 'Complete/Incomplete'),
        ('points', 'Points'),
        ('letter grade', 'Letter Grade'),
        ('GPA scale', 'GPA Scale'),
        ('not graded', 'Not Graded')
    )

    SUBMISSION_TYPE = (
        ('no submission', 'No  Submission'),
        ('online', 'Online'),
        ('on paper', 'On Paper'),
        ('external tool', 'External Tool')
    )

    name = models.CharField(max_length=30)
    description = RichTextUploadingField(blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    available_from = models.DateTimeField()
    available_until = models.DateTimeField()
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    for_course = models.ForeignKey(Course, on_delete=models.CASCADE)
    display_grades = models.CharField(choices=GRADES_DISPLAY, max_length=20, default='percentage')
    sub_type = models.CharField(choices=SUBMISSION_TYPE, max_length=20, default='no submission')

    max_grade = models.IntegerField()

    image = OptimizedImageField(
        upload_to=upload_path,
        optimized_image_output_size=(900, 900),
        optimized_image_resize_method='cover',  # 'thumbnail', 'cover' or None
        null=True,
        blank=True
    )

    def __str__(self):
        return f'{self.name}'

    def clean(self):
        role = Role.objects.filter(user=self.created_by)
        if role:
            if not (role[0].is_admin or role[0].is_teacher):
                raise ValidationError("Only Teacher Or Admin Can Create Assignment")
            if not self.for_course.user == self.created_by:
                raise ValidationError("Teacher of this course only can create assignments")
        else:
            raise ValidationError("Assign Role to the User")

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        students = StudentCourse.objects.filter(courses=self.for_course)
        for student in students:
            if student.registered:
                temp_object = StudentAssignment(user=student.user, assignment=self)
                temp_object.save()


# Comment Model - Separate from teacher and student model's
class Comment(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    content = models.TextField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-date']


class StudentAssignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='studentassignments')
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    marks = models.IntegerField(default=0)

lms/models/blog_model.py
# out sourced from https://github.com/CoreyMSchafer/code_snippets/blob/master/Django_Blog/11-Pagination/django_project/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lms:post-detail', kwargs={'pk': self.pk})

lms/models/dummy_model.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

limit_max_marks = 30_000.0
limit_min_marks = -10_000.0


class DummyStudent(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(
        primary_key=True, default='test@example.com', max_length=254, unique=True)

    def __str__(self):
        return f'{self.name}'


class DummyAssignment(models.Model):

    title = models.CharField(max_length=50)
    student = models.ForeignKey(DummyStudent, on_delete=models.CASCADE)
    max_mark = models.FloatField(default=0, validators=[MaxValueValidator(
        limit_max_marks), MinValueValidator(limit_min_marks)])
    alloted_mark = models.FloatField(default=0, validators=[MaxValueValidator(
        limit_max_marks), MinValueValidator(limit_min_marks)])
    grade = models.CharField(default='F', max_length=1)

    def __str__(self):
        return f'{self.student}, {self.title} got a {self.grade} with {self.alloted_mark}/{self.max_mark}'

lms/models/email_model.py
# Core Django imports.
from django.contrib.auth.models import User
from django.db import models

class Email(models.Model):
    student = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'emails')
    subject = models.CharField(max_length = 250, null = False, blank = False, unique = True)
    emailBody = models.CharField(max_length = 1000, null = False, blank = False, unique = True)

lms/templates/dashboard/dashboard_base.html
{% extends 'lms/lms_base.html' %}

{% block content %}
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% block dashboard-content %}
                {% endblock dashboard-content %}
            </div>
            {% if not is_profile_view %}
                <div class="col-md-3">
                    <div class="pt-lg-4">
                        {% block right-panel %}
                        {% endblock right-panel %}
                    </div>
                </div>
            {% endif %}
        </div>
    </main>
{% endblock content %}

lms/templates/dashboard/dashboard_home.html
{% extends 'dashboard/dashboard_base.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block dashboard-content %}
    <br>
    <h1 class="text-center">Dashboard</h1>
    <br>
    {% if is_student_view %}
        <h3 class="text-left">Registered Courses</h3>
        <div class="container-fluid">
            <div class="row">
                {% for student_course in registered_courses %}
                    <div class="col-sm-3">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ student_course.courses.title }}</h5>
                                <p class="card-text">{{ student_course.courses.description }}</p>
                                <form action="{% url 'lms:course-home' student_course.id %}" method="get"
                                      style="display:inline">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">View</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <br>
        <h3 class="text-left">Un-Registered Courses</h3>
        <div class="container-fluid">
            <div class="row">
                {% for course in unregistered_courses %}
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ course.title }}</h5>
                                <p class="card-text">{{ course.description }}</p>
                                <!-- <form action="{% url 'lms:course-home' course.id %}" method="get" style="display:inline">
                    {% csrf_token %}
                    <button class="btn btn-primary">View</button>
                  </form> -->
                                <form action="{% url 'lms:course_register' course.id %}" method="post"
                                      style="display:inline">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">Register</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    {% else %}
        <h3 class="text-left">Published Courses</h3>
        <div class="container-fluid">
            <div class="row">
                {% for course in published_courses %}
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ course.title }}</h5>
                                <p class="card-text">{{ course.description }}</p>
                                <form action="{% url 'lms:course-home' course.id %}" method="get"
                                      style="display:inline">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">View</button>
                                </form>
                                <form action="{% url 'lms:course_unpublish' course.id %}" method="post"
                                      style="display:inline">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">Un-Publish</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <br>
        <h3 class="text-left">Un-Published Courses</h3>
        <div class="container-fluid">
            <div class="row">
                {% for course in unpublished_courses %}
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ course.title }}</h5>
                                <p class="card-text">{{ course.description }}</p>
                                <form action="{% url 'lms:course-home' course.id %}" method="get"
                                      style="display:inline">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">View</button>
                                </form>
                                <form action="{% url 'lms:course_publish' course.id %}" method="post"
                                      style="display:inline">
                                    {% csrf_token %}
                                    <button class="btn btn-primary">Publish</button>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock dashboard-content %}

{% block right-panel %}
    {% if is_student_view %}
        <br>
        <div class='mx-2'>
            <h3>To Do</h3>
            <ul class="list-group">
                {% for student_assignment in assignments %}
                    <a href="#" class="list-group-item list-group-item-action">{{ student_assignment.assignment.name }}
                        <br><span>Course: </span><span>{{ student_assignment.assignment.for_course }}</span>
                        <br><span>Due Date: </span><span>{{ student_assignment.assignment.available_until }}</span></a>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <br>
        <div class="mx-2">
            <a class="btn btn-outline-primary" href="{% url 'lms:course_create' %}">Add course</a>
        </div>
        <div class='mx-2 mt-lg-4'>
            <h3>Coming Up</h3>
            <ul class="list-group">
                {% for assignment in assignments %}
                    <a href="#" class="list-group-item list-group-item-action">{{ assignment.name }}
                        <br><span>Course: </span><span>{{ assignment.for_course }}</span>
                        <br><span>Due Date: </span><span>{{ assignment.available_until }}</span></a>
                {% endfor %}
                {% for quiz in quizzes %}
                    <a href="#" class="list-group-item list-group-item-action">{{ quiz.Quizname }}
                        <br><span>Course: </span><span>{{ quiz.course }}</span>
                        <br><span>Due Date: </span><span>{{ quiz.Until }}</span></a>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock right-panel %}

lms/templates/dashboard/landing_base.html
{% extends 'lms/lms_base.html' %}

{% block content %}
    <h1 class="text-center pt-3 pb-3 border-bottom">Welcome to LMX</h1>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
{% endblock scripts %}

lms/templates/dashboard/profile.html
{% extends "dashboard/dashboard_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <br>
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" style="width:20%;height:20%">
        <div class="media-body">
          <br>
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
          <p class="text-secondary">{{ role }}</p>
        </div>
      </div>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <br>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
    </div>
{% endblock content %}