lms/urls.py
# Core Django imports.
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include

# LMS app imports
from lms.views.account.login_view import UserLoginView
from lms.views.account.logout_view import UserLogoutView
from lms.views.account.register_view import (
    ActivateView,
    AccountActivationSentView,
    UserRegisterView,
)
from lms.views.account.subscriber_view import subscribe, subscribe_confirm, subscribe_delete, sub_delete
from lms.views.assignment.assignment_views import (
    AssignmentHomeView,
    AssignmentDetailView,
    AssignmentCreateView,
    AssignmentUpdateView,
    AssignmentDeleteView,
    CommentCreateView, AssignmentHomeStudentView, AssignmentDetailStudentView,
)
from lms.views.blog.blog_view import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from lms.views.course.course_publish_views import (
    CoursePublishView,
    CourseUnPublishView
)
from lms.views.course.course_registration_views import (
    CourseRegistrationView,
)
from lms.views.course.course_views import (
    CourseListView,
    GradeBookCourseView,
    StudentGradeBookCourseView, CourseCreateView
    # table_download
)
from lms.views.course.grading_scheme_view import (
    GradingSchemeUpdateView,
    GradingSchemeCreateView
)
from lms.views.course.group_creation_view import (
    GroupCreationRequestView,
    GroupCreationRequestSentView,
    ViewGroupsView
)
from lms.views.course.mail_to_admin_view import (
    MailToAdminView

)
from lms.views.course.settings_view import (
    CourseDetailsView,
    CourseManageView,
    CourseSectionsView,
    CourseStatisticsView
)
from lms.views.dashboard.dashboard_views import (
    DashboardHomeView,
    DashboardProfileView,
    dashboard_list,
    dashboard_details,
    dashboard_subscribe
)
from lms.views.notification.notification_settings_view import (
    NotificationSettingsView,
)
from lms.views.quiz.quiz_views import (
    compute_stats,
    fetch_questions_one_at_a_time,
    fetch_questions,
    quiz_home,
    quiz_detail,
    preview_quiz,
    enter_quiz_comment,
    quiz_publish, QuizCreateView, QuizUpdateView, QuizDeleteView,
    QuizQuestionCreateView, QuizQuestionUpdateView, QuizQuestionDeleteView
)

# Specifies the app name for name spacing.
app_name = "lms"

# lms/urls.py
urlpatterns = [

    # LMS URLS #

    # /home/
    path(
        route='course/<int:pk>/',
        view=CourseListView.as_view(),
        name='course-home'
    ),

    # /home/
    path(
        route='course/',
        view=CourseListView.as_view(),
        name='course-home'
    ),

    # Blog URLS #

    # /home/blog
    path(
        route='blog/',
        view=PostListView.as_view(),
        name='blog-home'
    ),

    path(
        route='blog/user/<str:username>/',
        view=UserPostListView.as_view(),
        name='user-posts'
    ),

    path(
        route='blog/post/<int:pk>/',
        view=PostDetailView.as_view(),
        name='post-detail'
    ),

    path(
        route='blog/post/new/',
        view=PostCreateView.as_view(),
        name='post-create'
    ),

    path(
        route='blog/post/<int:pk>/update/',
        view=PostUpdateView.as_view(),
        name='post-update'
    ),

    path(
        route='blog/post/<int:pk>/delete/',
        view=PostDeleteView.as_view(),
        name='post-delete'
    ),

    # ACCOUNT URLS #

    # /account/login/
    path(
        route='account/login/',
        view=UserLoginView.as_view(),
        name='login'
    ),

    # /account/login/
    path(
        route='account/register/',
        view=UserRegisterView.as_view(),
        name='register'
    ),

    # /account/logout/
    path(
        route='account/logout/',
        view=UserLogoutView.as_view(),
        name='logout'
    ),

    path(route='account_activation_sent/',
         view=AccountActivationSentView.as_view(),
         name='account_activation_sent'
         ),

    path(route='activate/<uidb64>/<token>/',
         view=ActivateView.as_view(),
         name='activate'
         ),

    # DASHBOARD URLS #

    # /
    path('', dashboard_list, name='home'),
    path('<int:page>', dashboard_list, name='home'),
    path('coursedetails/<int:pk>/', dashboard_details),
    path('subscribe/<int:pk>/', dashboard_subscribe),

    # /author/dashboard/home/
    path(
        route="dashboard/home/",
        view=DashboardHomeView.as_view(),
        name="dashboard_home"
    ),

    # /author/dashboard/profile/
    path(
        route="dashboard/profile/",
        view=DashboardProfileView.as_view(),
        name="dashboard_profile"
    ),

    # /author/course/register
    path(
        route="course/register/<int:pk>/",
        view=CourseRegistrationView.as_view(),
        name="course_register"
    ),

    # /author/course/publish
    path(
        route="course/publish/<int:pk>/",
        view=CoursePublishView.as_view(),
        name="course_publish"
    ),

    # /author/course/unpublish
    path(
        route="course/unpublish/<int:pk>/",
        view=CourseUnPublishView.as_view(),
        name="course_unpublish"
    ),

    path(
        route="course/create/",
        view=CourseCreateView.as_view(),
        name="course_create"
    ),
    # /author/notification/
    path(
        route="notifications/",
        view=NotificationSettingsView.as_view(),
        name="notification_settings"
    ),

    # COURSE SETTINGS URLS #

    path(
        route="course/<int:pk>/details/",
        view=CourseDetailsView.as_view(),
        name="course_details"
    ),
    path(
        route="course/<int:pk>/manage/",
        view=CourseManageView.as_view(),
        name="course_manage"
    ),
    path(
        route="course/<int:pk>/sections/",
        view=CourseSectionsView.as_view(),
        name="course_sections"
    ),
    path(
        route="course/<int:pk>/statistics/",
        view=CourseStatisticsView.as_view(),
        name="course_statistics"
    ),
    path(
        route="course/<int:pk>/grading_scheme/new/",
        view=GradingSchemeCreateView.as_view(),
        name="course_grading_scheme_create"
    ),
    path(
        route="course/<int:pk>/grading_scheme/update/",
        view=GradingSchemeUpdateView.as_view(),
        name="course_grading_scheme_update"
    ),

    # COURSE STUDENT - Group CREATION REQUEST
    path(
        route="course/<int:pk>/group_creation_request/",
        view=GroupCreationRequestView.as_view(),
        name="group_creation_request"
    ),
    path(route='group_request/<int:ck>/<uidb64>/<token>/',
         view=GroupCreationRequestSentView.as_view(),
         name='group_request'
         ),

    # View GROUPS -
    path(
        route="course/<int:pk>/view_groups/",
        view=ViewGroupsView.as_view(),
        name="view_groups"
    ),

    # COURSE STUDENT -  Mail To Admin
    path(
        route="course/<int:pk>/mail_to_admin/",
        view=MailToAdminView.as_view(),
        name="mail_to_admin"
    ),

    # COURSE GRADEBOOK - Teacher's View
    path(
        route="course/<int:course_id>/grades/",
        view=GradeBookCourseView.as_view(),
        name='gradebook-course'
    ),

    path(
        route="course/<int:course_id>/student_grades/",
        view=StudentGradeBookCourseView.as_view(),
        name='gradebook-course-student'
    ),

    # By Quiz Teacher View Team.[Start]
    path('course/<int:course_id>/quiz/course_stats/', compute_stats, name="compute_stats"),

    path('course/<int:course_id>/quiz/<int:pk>/one_at_a_time/', fetch_questions_one_at_a_time,
         name="fetch_questions_one_at_a_time"),

    path('course/<int:course_id>/quiz/<int:pk>/fetch_questions/', fetch_questions, name="fetch_questions"),

    path('course/<int:course_id>/quiz/home/', quiz_home, name="quiz_home"),

    path('course/<int:course_id>/quiz/create/', QuizCreateView.as_view(), name="quiz_create"),
    path('course/<int:course_id>/quiz/<int:pk>/update/', QuizUpdateView.as_view(), name="quiz_update"),
    path('course/<int:course_id>/quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name="quiz_delete"),

    path('course/<int:course_id>/quiz/<int:quiz_id>/question/create', QuizQuestionCreateView.as_view(),
         name="quiz_question_create"),
    path('course/<int:course_id>/quiz/<int:quiz_id>/question/<int:pk>/update/', QuizQuestionUpdateView.as_view(),
         name="quiz_question_update"),
    path('course/<int:course_id>/quiz/<int:quiz_id>/question/<int:pk>/delete/', QuizQuestionDeleteView.as_view(),
         name="quiz_question_delete"),

    path('course/<int:course_id>/quiz/<int:pk>/detail/', quiz_detail, name="quiz_view"),

    path('course/<int:course_id>/quiz/<int:pk>/preview/', preview_quiz, name="preview_quiz"),

    path('course/<int:course_id>/quiz/<int:pk>/enter_quiz_comment/', enter_quiz_comment, name="enter_quiz_comment"),

    path('course/<int:course_id>/quiz/<int:pk>/publish/', quiz_publish, name='quiz_publish'),
    # By Quiz Teacher View Team.[End]

    # Assignment Views
    path(
        route="course/<int:pkcourse>/student_assignment/home/",
        view=AssignmentHomeStudentView.as_view(),
        name="assignment_student_home"
    ),

    path(
        route="course/<int:pkcourse>/student_assignment/home/<int:pk>/",
        view=AssignmentDetailStudentView.as_view(),
        name="assignment_student_detail"
    ),

    path(
        route="course/<int:pkcourse>/assignment/home/",
        view=AssignmentHomeView.as_view(),
        name="assignment_home"
    ),

    path(
        route="course/<int:pkcourse>/assignment/home/<int:pk>/",
        view=AssignmentDetailView.as_view(),
        name="assignment_detail"
    ),

    path(
        route="course/<int:pkcourse>/assignment/create/",
        view=AssignmentCreateView.as_view(),
        name="assignment_create"
    ),
    path(
        route='course/<int:pkcourse>/assignment/<int:pk>/update/',

lmx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls', namespace='lms')),

    # Url for password reset.
    path('account/password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'),
         name='password_reset'),

    # Url for successful password reset.
    path('account/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    # Url for successful password reset confirm.
    path('account/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),

    # Url for password reset done.
    path('account/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # Url for social authentication.
    path('oauth/', include('social_django.urls', namespace="social")),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ]

# if not production add media url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "LMX Admin"
admin.site.site_title = "LMX Admin Portal"
admin.site.index_title = "Welcome to LMX Site Portal"

lms/models/course_model.py
# Core Django imports.
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from lms.models.user_role_model import Role


class GradingSchemeName(models.Model):
    """
    Model to capture various grading schemes.
    Courses will be able to choose from these grading schemes
    """
    name = models.CharField(max_length=250, null=False, blank=False, unique=True)

    def __str__(self):
        return f'Grading Scheme {self.name}'


class GradingScheme(models.Model):
    """
    Model to capture various grading schemes.
    Courses will be able to choose from these grading schemes
    """
    scheme_name = models.ForeignKey(to=GradingSchemeName, on_delete=models.CASCADE)
    grade = models.CharField(max_length=250, null=False, blank=False)
    score_range_begin = models.SmallIntegerField()
    score_range_end = models.SmallIntegerField()

    def __str__(self):
        return f'{self.scheme_name}, Grade: {self.grade}, Scores: [{self.score_range_begin}, {self.score_range_end})'

    def clean(self):
        super(GradingScheme, self).clean()

        if self.score_range_end and self.score_range_begin:
            if self.score_range_end < self.score_range_begin:
                raise ValidationError('Range Error: Score end value is less that the score begin value!')

    # # Constraints to ensure that a duplicate entry is not present with scheme name and grade
    # class Meta:
    #     unique_together = ('scheme_name', 'grade',)


class Course(models.Model):
    """
    Model to capture all the course details
    credits: default.png online school by Becris from the Noun Project
    """
    title = models.CharField(max_length=250, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses')
    description = models.TextField(null=True)
    published = models.BooleanField(default=False)
    thumbnail = models.ImageField(default='default.png', upload_to='course_thumbnails', null=True, blank=True)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    grading_scheme = models.ForeignKey(to=GradingSchemeName, on_delete=models.SET_NULL, null=True, blank=True)
    allow_self_enroll = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def clean(self):
        role = Role.objects.filter(user=self.user)
        if role:
            if not (role[0].is_admin or role[0].is_teacher):
                raise ValidationError("Only Teacher Or Admin Can Create Courses")
        else:
            raise ValidationError("Assign Role to the User")

        if self.start_date > self.end_date:
            raise ValidationError('Start date cannot be greater than the end date')


class Section(models.Model):
    """
    Students belonging to each course can be further sub-divided into sections
    """
    section_name = models.CharField(max_length=250, null=True, blank=False, unique=True)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'Section {self.section_name} - {self.course}'

    # Constraints to ensure that a duplicate entry is not present with section_name and course
    class Meta:
        unique_together = ('section_name', 'course',)


class Group(models.Model):
    """
    Students belonging to each course can be further sub-divided into groups by themselves:
    Only difference between groups and sections is Section is teacher created, groups is student created
    """
    group_name = models.CharField(max_length=250, null=True, blank=False, unique=True)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=False)

    def __str__(self):
        return f'Group {self.group_name} - {self.course}'

    # Constraints to ensure that a duplicate entry is not present with group_name and course
    class Meta:
        unique_together = ('group_name', 'course',)


class StudentCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='studentcourses')
    courses = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='courses')
    registered = models.BooleanField(default=False)

    section = models.ForeignKey(Section, on_delete=models.SET_NULL, blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} is associated with {self.courses.title}'

    def clean(self):
        role = Role.objects.filter(user=self.user)
        if role:
            if role[0].is_admin or role[0].is_teacher or role[0].is_teaching_assistant:
                raise ValidationError("Only Student can register to the courses")
        else:
            raise ValidationError("Assign Role to the User")

        if not self.courses.published:
            raise ValidationError("Only Published courses can be selected")

    # Constraints to ensure that a student cannot enroll into the same course more than once
    class Meta:
        unique_together = ('user', 'courses',)


class CourseSubscribe(models.Model):
    """
    Students belonging to each course can be further sub-divided into sections
    """
    email_id = models.EmailField(max_length=250, null=False, blank=False, unique=False)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'Email {self.email_id} - {self.course}'

    # Constraints to ensure that a duplicate entry is not present with section_name and course
    class Meta:
        unique_together = ('email_id', 'course',)

lms/templates/dashboard/landing/coursedetails.html
<!DOCTYPE html>
{% extends 'dashboard/landing_base.html' %}
{% load static %}
{% block title %}
    Home
{% endblock title %}


{% block content %}

    <div class="p-2 mb-2 bg-secondary text-white text-center font-weight-bold"><h4>Course Details</h4></div>
    <div class="container jumbotron">
    <div class="card mb-3 align-items-center" style="width: 50rem;"">
    <table class="table table-striped table-hover table-bordered">
      {% for course in course_list %}
      <tbody>
      
      <tr>
        <td><b>Title</b></td><td>{{course.title}}</td>
      </tr>
      <tr>
        <td><b>Description</b></td><td>{{course.description}}</td>

      </tr>
      <tr>
        <td><b>Published</b></td><td>{{course.published}}</td>

      </tr>
      <tr>

        <td><b>StartDate</b></td><td>{{course.start_date}}</td>
      </tr>
      <tr>

        <td><b>EndDate</b></td><td>{{course.end_date}}</td>
      </tr>
      <tr>

        <td><b>Created by</b></td><td>{{course.user_id}}</td>
      </tr>
      <tr>
        <td><b>Grading Scheme</b></td><td>{{course.grading_scheme_id}}</td>
      </tr>
      
      </tbody>
      {% endfor %}
    </table>
  </div>
</div>
{% endblock content %}

lms/templates/dashboard/landing/group_creation_request.html
{% extends 'lms/lms_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
 Group Creation Request
{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="text-center pt-3 pb-3 border-bottom">Create Group/Request Members To join</h1>
    <div class="bd-callout bd-callout-info">
        <p class="font-weight-normal text-muted">
            This form is to both create group , request members and if you own a group already then type in the exact group name and request the members
        </p>
    </div>

    <div class="pt-3 pb-3>">
		<div class="form-group">
                <form action="{% url 'lms:group_creation_request' pk %}"  class="form-horizontal" method="post" novalidate>
                    {% csrf_token %}

                    <fieldset class="form-group">
                        {{ form|as_crispy_errors }}
                        <div class="row mb-lg-3 mt-lg-3">
                            <div class="col">
                                Group Name
                            </div>

                            <div class="col-lg-9">
                                {{ group_creation_form.name|as_crispy_field }}
                            </div>
                        </div>
		
                        <div class="row mb-lg-3 mt-lg-3">
                            <div class="col">
                                Student Email
                            </div>

                            <div class="col-lg-9">
                                {{ group_creation_form.student_email |as_crispy_field }}
                            </div>
                        </div>

                
                    </fieldset>
                    <div class="border-top  pt-3 pb-5">
                     
                     <button class="btn btn-outline-success" type="submit">Send Request</button>
                 </div>
		</form>
		</div>

{% endblock content %}

lms/templates/dashboard/landing/group_creation_request_email.html
{% autoescape off %}
Hi {{ user.username }},
{{from_user}}  from {{course}} has requested to create a group.


Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'lms:group_request' ck=course_id uidb64=uid token=token %}
{% endautoescape %}

lms/templates/dashboard/landing/home.html
{% extends 'dashboard/landing_base.html' %}

{% block title %}
    Home
{% endblock title %}


{% block content %}

    <div class="container text-dark">
        <h1 class="text-center pt-3 pb-3 mb-lg-5 mt-lg-3 border-bottom">Welcome to LMX</h1>

        <div class="row">
            {% for course in course_list %}
                <div class="col-md-3 d-flex align-items-stretch">
                    <div class="card mb-3" style="width: 15rem;" id={{ course.id }}>
                        <div class="card-body">
                            <h6 class="card-title alert alert-success">{{ forloop.counter0|add:"1" }}. {{ course.title }}</h6>

                            <img class="card-img-top embed-responsive-item"
                                 src={{ course.thumbnail.url }} alt={{ course.thumbnail.url }}>
                            <h6 class="card-text text-center">Self Enroll
                                {% if course.allow_self_enroll == True %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                    </svg>
                                {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z"/>
                                    </svg>
                                {% endif %}
                            </h6>
                        </div>
                        <div class="card-footer bg-success border-success">
                            <!-- <h6 class="card-subtitle mb-2">created by- {{course.user}}</h6> -->
                            <div class="row">
                                <div class="col-md-6">
                                    <p class="card-text" style="transform: rotate(0);"><a style="text-decoration: none"
                                                                                          href="coursedetails/{{ course.id }}"
                                                                                          class="stretched-link text-light">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor" class="bi bi-menu-app" viewBox="0 0 16 16">
                                            <path d="M0 1.5A1.5 1.5 0 0 1 1.5 0h2A1.5 1.5 0 0 1 5 1.5v2A1.5 1.5 0 0 1 3.5 5h-2A1.5 1.5 0 0 1 0 3.5v-2zM1.5 1a.5.5 0 0 0-.5.5v2a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-.5-.5h-2zM0 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V8zm1 3v2a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2H1zm14-1V8a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v2h14zM2 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                                        </svg>&nbsp;More Info</a>
                                    </p>
                                </div>
                                <div class="col-md-6 align-self-end">
                                    <button type="button" class="btn btn-primary" data-toggle="modal"
                                            data-target="#cModal" onclick="subscribe({{ course.id }})">
                                        subscribe
                                    </button>

                                    <!-- basic modal -->
                                    <div class="modal fade" id="cModal" tabindex="-1" role="dialog"
                                         aria-labelledby="cModal" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="myModalLabel">{{ course.title }}</h4>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                            aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <h3>Modal content</h3>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                                        Close
                                                    </button>
                                                    <button type="button" class="btn btn-primary">Save changes</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <script>
                                        $(document).ready(function () {
                                            $("#cModal").modal();
                                        });

                                        function subscribe(id) {
                                            console.log('id is', id);
                                            location.href = `subscribe/${id}`;
                                        }
                                    </script>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


        <div class="mt-lg-4">
            <!--Pagination-->
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if course_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ movies.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                    {% endif %}
                    {% for i in course_list.paginator.page_range %}
                        {% if course_list.number == i %}
                            <li class="page-item active" aria-current="page">
              <span class="page-link">
                {{ i }}
                <span class="sr-only">(current)</span>
              </span>
                            </li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if course_list.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ course_list.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

{% endblock content %}

lms/templates/dashboard/landing/mail_to_admin.html
{% extends 'lms/lms_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Mail To Admin
{% endblock title %}

{% block content %}
<div class="container">
    <h1 class="text-center pt-3 pb-3 border-bottom">Mail To Admin</h1>
		
		
  		
	

               
    <div class="pt-3 pb-3>">
		<div class="form-group">
                <form action="{% url 'lms:mail_to_admin' pk %}"  class="form-horizontal" method="post" novalidate>
                    {% csrf_token %}
                    <fieldset class="form-group">
                        {{ form|as_crispy_errors }}
                        <div class="row mb-lg-3 mt-lg-3">
                            <div class="col">
                                Subject
                            </div>

                            <div class="col-lg-9">
                                {{ mail_to_admin_form.subject|as_crispy_field }}
                            </div>
                        </div>

                            <div class="row mb-lg-3 mt-lg-3">
                                <div class="col">
                                    Mail body
                                </div>
    
                                <div class="col-lg-9">
                                    {{ mail_to_admin_form.media}}
                                    {{ mail_to_admin_form.body|safe }}
                                </div>
                            </div>

                            <div class="row mb-lg-3 mt-lg-3">
                                <div class="col">
                                    Teacher
                                </div>
    
                                <div class="col-lg-9">
                                    {{ mail_to_admin_form.staff_email |as_crispy_field }}
                                </div>
                            </div>
                    
					
                    
                   </fieldset>
                   <div class="border-top  pt-3 pb-5">
                    
                    <button class="btn btn-outline-success" type="submit">Send Mail</button>
                </div>

                   
		</form>
		</div>

{% endblock content %}