lms/urls.py
# Core Django imports.
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include

# LMS app imports
from lms.views.account.login_view import UserLoginView
from lms.views.account.logout_view import UserLogoutView
from lms.views.account.register_view import (
    ActivateView,
    AccountActivationSentView,
    UserRegisterView,
)
from lms.views.account.subscriber_view import subscribe, subscribe_confirm, subscribe_delete, sub_delete
from lms.views.assignment.assignment_views import (
    AssignmentHomeView,
    AssignmentDetailView,
    AssignmentCreateView,
    AssignmentUpdateView,
    AssignmentDeleteView,
    CommentCreateView, AssignmentHomeStudentView, AssignmentDetailStudentView,
)
from lms.views.blog.blog_view import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from lms.views.course.course_publish_views import (
    CoursePublishView,
    CourseUnPublishView
)
from lms.views.course.course_registration_views import (
    CourseRegistrationView,
)
from lms.views.course.course_views import (
    CourseListView,
    GradeBookCourseView,
    StudentGradeBookCourseView, CourseCreateView
    # table_download
)
from lms.views.course.grading_scheme_view import (
    GradingSchemeUpdateView,
    GradingSchemeCreateView
)
from lms.views.course.group_creation_view import (
    GroupCreationRequestView,
    GroupCreationRequestSentView,
    ViewGroupsView
)
from lms.views.course.mail_to_admin_view import (
    MailToAdminView

)
from lms.views.course.settings_view import (
    CourseDetailsView,
    CourseManageView,
    CourseSectionsView,
    CourseStatisticsView
)
from lms.views.dashboard.dashboard_views import (
    DashboardHomeView,
    DashboardProfileView,
    dashboard_list,
    dashboard_details,
    dashboard_subscribe
)
from lms.views.notification.notification_settings_view import (
    NotificationSettingsView,
)
from lms.views.quiz.quiz_views import (
    compute_stats,
    fetch_questions_one_at_a_time,
    fetch_questions,
    quiz_home,
    quiz_detail,
    preview_quiz,
    enter_quiz_comment,
    quiz_publish, QuizCreateView, QuizUpdateView, QuizDeleteView,
    QuizQuestionCreateView, QuizQuestionUpdateView, QuizQuestionDeleteView
)

# Specifies the app name for name spacing.
app_name = "lms"

# lms/urls.py
urlpatterns = [

    # LMS URLS #

    # /home/
    path(
        route='course/<int:pk>/',
        view=CourseListView.as_view(),
        name='course-home'
    ),

    # /home/
    path(
        route='course/',
        view=CourseListView.as_view(),
        name='course-home'
    ),

    # Blog URLS #

    # /home/blog
    path(
        route='blog/',
        view=PostListView.as_view(),
        name='blog-home'
    ),

    path(
        route='blog/user/<str:username>/',
        view=UserPostListView.as_view(),
        name='user-posts'
    ),

    path(
        route='blog/post/<int:pk>/',
        view=PostDetailView.as_view(),
        name='post-detail'
    ),

    path(
        route='blog/post/new/',
        view=PostCreateView.as_view(),
        name='post-create'
    ),

    path(
        route='blog/post/<int:pk>/update/',
        view=PostUpdateView.as_view(),
        name='post-update'
    ),

    path(
        route='blog/post/<int:pk>/delete/',
        view=PostDeleteView.as_view(),
        name='post-delete'
    ),

    # ACCOUNT URLS #

    # /account/login/
    path(
        route='account/login/',
        view=UserLoginView.as_view(),
        name='login'
    ),

    # /account/login/
    path(
        route='account/register/',
        view=UserRegisterView.as_view(),
        name='register'
    ),

    # /account/logout/
    path(
        route='account/logout/',
        view=UserLogoutView.as_view(),
        name='logout'
    ),

    path(route='account_activation_sent/',
         view=AccountActivationSentView.as_view(),
         name='account_activation_sent'
         ),

    path(route='activate/<uidb64>/<token>/',
         view=ActivateView.as_view(),
         name='activate'
         ),

    # DASHBOARD URLS #

    # /
    path('', dashboard_list, name='home'),
    path('<int:page>', dashboard_list, name='home'),
    path('coursedetails/<int:pk>/', dashboard_details),
    path('subscribe/<int:pk>/', dashboard_subscribe),

    # /author/dashboard/home/
    path(
        route="dashboard/home/",
        view=DashboardHomeView.as_view(),
        name="dashboard_home"
    ),

    # /author/dashboard/profile/
    path(
        route="dashboard/profile/",
        view=DashboardProfileView.as_view(),
        name="dashboard_profile"
    ),

    # /author/course/register
    path(
        route="course/register/<int:pk>/",
        view=CourseRegistrationView.as_view(),
        name="course_register"
    ),

    # /author/course/publish
    path(
        route="course/publish/<int:pk>/",
        view=CoursePublishView.as_view(),
        name="course_publish"
    ),

    # /author/course/unpublish
    path(
        route="course/unpublish/<int:pk>/",
        view=CourseUnPublishView.as_view(),
        name="course_unpublish"
    ),

    path(
        route="course/create/",
        view=CourseCreateView.as_view(),
        name="course_create"
    ),
    # /author/notification/
    path(
        route="notifications/",
        view=NotificationSettingsView.as_view(),
        name="notification_settings"
    ),

    # COURSE SETTINGS URLS #

    path(
        route="course/<int:pk>/details/",
        view=CourseDetailsView.as_view(),
        name="course_details"
    ),
    path(
        route="course/<int:pk>/manage/",
        view=CourseManageView.as_view(),
        name="course_manage"
    ),
    path(
        route="course/<int:pk>/sections/",
        view=CourseSectionsView.as_view(),
        name="course_sections"
    ),
    path(
        route="course/<int:pk>/statistics/",
        view=CourseStatisticsView.as_view(),
        name="course_statistics"
    ),
    path(
        route="course/<int:pk>/grading_scheme/new/",
        view=GradingSchemeCreateView.as_view(),
        name="course_grading_scheme_create"
    ),
    path(
        route="course/<int:pk>/grading_scheme/update/",
        view=GradingSchemeUpdateView.as_view(),
        name="course_grading_scheme_update"
    ),

    # COURSE STUDENT - Group CREATION REQUEST
    path(
        route="course/<int:pk>/group_creation_request/",
        view=GroupCreationRequestView.as_view(),
        name="group_creation_request"
    ),
    path(route='group_request/<int:ck>/<uidb64>/<token>/',
         view=GroupCreationRequestSentView.as_view(),
         name='group_request'
         ),

    # View GROUPS -
    path(
        route="course/<int:pk>/view_groups/",
        view=ViewGroupsView.as_view(),
        name="view_groups"
    ),

    # COURSE STUDENT -  Mail To Admin
    path(
        route="course/<int:pk>/mail_to_admin/",
        view=MailToAdminView.as_view(),
        name="mail_to_admin"
    ),

    # COURSE GRADEBOOK - Teacher's View
    path(
        route="course/<int:course_id>/grades/",
        view=GradeBookCourseView.as_view(),
        name='gradebook-course'
    ),

    path(
        route="course/<int:course_id>/student_grades/",
        view=StudentGradeBookCourseView.as_view(),
        name='gradebook-course-student'
    ),

    # By Quiz Teacher View Team.[Start]
    path('course/<int:course_id>/quiz/course_stats/', compute_stats, name="compute_stats"),

    path('course/<int:course_id>/quiz/<int:pk>/one_at_a_time/', fetch_questions_one_at_a_time,
         name="fetch_questions_one_at_a_time"),

    path('course/<int:course_id>/quiz/<int:pk>/fetch_questions/', fetch_questions, name="fetch_questions"),

    path('course/<int:course_id>/quiz/home/', quiz_home, name="quiz_home"),

    path('course/<int:course_id>/quiz/create/', QuizCreateView.as_view(), name="quiz_create"),
    path('course/<int:course_id>/quiz/<int:pk>/update/', QuizUpdateView.as_view(), name="quiz_update"),
    path('course/<int:course_id>/quiz/<int:pk>/delete/', QuizDeleteView.as_view(), name="quiz_delete"),

    path('course/<int:course_id>/quiz/<int:quiz_id>/question/create', QuizQuestionCreateView.as_view(),
         name="quiz_question_create"),
    path('course/<int:course_id>/quiz/<int:quiz_id>/question/<int:pk>/update/', QuizQuestionUpdateView.as_view(),
         name="quiz_question_update"),
    path('course/<int:course_id>/quiz/<int:quiz_id>/question/<int:pk>/delete/', QuizQuestionDeleteView.as_view(),
         name="quiz_question_delete"),

    path('course/<int:course_id>/quiz/<int:pk>/detail/', quiz_detail, name="quiz_view"),

    path('course/<int:course_id>/quiz/<int:pk>/preview/', preview_quiz, name="preview_quiz"),

    path('course/<int:course_id>/quiz/<int:pk>/enter_quiz_comment/', enter_quiz_comment, name="enter_quiz_comment"),

    path('course/<int:course_id>/quiz/<int:pk>/publish/', quiz_publish, name='quiz_publish'),
    # By Quiz Teacher View Team.[End]

    # Assignment Views
    path(
        route="course/<int:pkcourse>/student_assignment/home/",
        view=AssignmentHomeStudentView.as_view(),
        name="assignment_student_home"
    ),

    path(
        route="course/<int:pkcourse>/student_assignment/home/<int:pk>/",
        view=AssignmentDetailStudentView.as_view(),
        name="assignment_student_detail"
    ),

    path(
        route="course/<int:pkcourse>/assignment/home/",
        view=AssignmentHomeView.as_view(),
        name="assignment_home"
    ),

    path(
        route="course/<int:pkcourse>/assignment/home/<int:pk>/",
        view=AssignmentDetailView.as_view(),
        name="assignment_detail"
    ),

    path(
        route="course/<int:pkcourse>/assignment/create/",
        view=AssignmentCreateView.as_view(),
        name="assignment_create"
    ),
    path(
        route='course/<int:pkcourse>/assignment/<int:pk>/update/',

lmx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lms.urls', namespace='lms')),

    # Url for password reset.
    path('account/password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password_reset.html'),
         name='password_reset'),

    # Url for successful password reset.
    path('account/password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password_reset_done.html'),
         name='password_reset_done'),

    # Url for successful password reset confirm.
    path('account/password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),

    # Url for password reset done.
    path('account/password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # Url for social authentication.
    path('oauth/', include('social_django.urls', namespace="social")),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    ]

# if not production add media url
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Modifies default django admin titles and headers with custom app detail.
admin.site.site_header = "LMX Admin"
admin.site.site_title = "LMX Admin Portal"
admin.site.index_title = "Welcome to LMX Site Portal"

lms/models/course_model.py
# Core Django imports.
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from lms.models.user_role_model import Role


class GradingSchemeName(models.Model):
    """
    Model to capture various grading schemes.
    Courses will be able to choose from these grading schemes
    """
    name = models.CharField(max_length=250, null=False, blank=False, unique=True)

    def __str__(self):
        return f'Grading Scheme {self.name}'


class GradingScheme(models.Model):
    """
    Model to capture various grading schemes.
    Courses will be able to choose from these grading schemes
    """
    scheme_name = models.ForeignKey(to=GradingSchemeName, on_delete=models.CASCADE)
    grade = models.CharField(max_length=250, null=False, blank=False)
    score_range_begin = models.SmallIntegerField()
    score_range_end = models.SmallIntegerField()

    def __str__(self):
        return f'{self.scheme_name}, Grade: {self.grade}, Scores: [{self.score_range_begin}, {self.score_range_end})'

    def clean(self):
        super(GradingScheme, self).clean()

        if self.score_range_end and self.score_range_begin:
            if self.score_range_end < self.score_range_begin:
                raise ValidationError('Range Error: Score end value is less that the score begin value!')

    # # Constraints to ensure that a duplicate entry is not present with scheme name and grade
    # class Meta:
    #     unique_together = ('scheme_name', 'grade',)


class Course(models.Model):
    """
    Model to capture all the course details
    credits: default.png online school by Becris from the Noun Project
    """
    title = models.CharField(max_length=250, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses')
    description = models.TextField(null=True)
    published = models.BooleanField(default=False)
    thumbnail = models.ImageField(default='default.png', upload_to='course_thumbnails', null=True, blank=True)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    grading_scheme = models.ForeignKey(to=GradingSchemeName, on_delete=models.SET_NULL, null=True, blank=True)
    allow_self_enroll = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def clean(self):
        role = Role.objects.filter(user=self.user)
        if role:
            if not (role[0].is_admin or role[0].is_teacher):
                raise ValidationError("Only Teacher Or Admin Can Create Courses")
        else:
            raise ValidationError("Assign Role to the User")

        if self.start_date > self.end_date:
            raise ValidationError('Start date cannot be greater than the end date')


class Section(models.Model):
    """
    Students belonging to each course can be further sub-divided into sections
    """
    section_name = models.CharField(max_length=250, null=True, blank=False, unique=True)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'Section {self.section_name} - {self.course}'

    # Constraints to ensure that a duplicate entry is not present with section_name and course
    class Meta:
        unique_together = ('section_name', 'course',)


class Group(models.Model):
    """
    Students belonging to each course can be further sub-divided into groups by themselves:
    Only difference between groups and sections is Section is teacher created, groups is student created
    """
    group_name = models.CharField(max_length=250, null=True, blank=False, unique=True)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=False)

    def __str__(self):
        return f'Group {self.group_name} - {self.course}'

    # Constraints to ensure that a duplicate entry is not present with group_name and course
    class Meta:
        unique_together = ('group_name', 'course',)


class StudentCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='studentcourses')
    courses = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='courses')
    registered = models.BooleanField(default=False)

    section = models.ForeignKey(Section, on_delete=models.SET_NULL, blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} is associated with {self.courses.title}'

    def clean(self):
        role = Role.objects.filter(user=self.user)
        if role:
            if role[0].is_admin or role[0].is_teacher or role[0].is_teaching_assistant:
                raise ValidationError("Only Student can register to the courses")
        else:
            raise ValidationError("Assign Role to the User")

        if not self.courses.published:
            raise ValidationError("Only Published courses can be selected")

    # Constraints to ensure that a student cannot enroll into the same course more than once
    class Meta:
        unique_together = ('user', 'courses',)


class CourseSubscribe(models.Model):
    """
    Students belonging to each course can be further sub-divided into sections
    """
    email_id = models.EmailField(max_length=250, null=False, blank=False, unique=False)
    course = models.ForeignKey(to=Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'Email {self.email_id} - {self.course}'

    # Constraints to ensure that a duplicate entry is not present with section_name and course
    class Meta:
        unique_together = ('email_id', 'course',)

lms/templates/dashboard/landing/settings/course_details_tab.html
{% extends 'lms/course/settings/settings_base.html' %}
{% load crispy_forms_tags %}

{% block main-content %}
    <div class="container">
        <h1 class="text-center pt-3 pb-3 border-bottom">Course Details</h1>

        <h5 class="pt-3 pb-1">View/Update the Course Details</h5>

        <div class="pt-3 pb-3>">
            <form action="{% url 'lms:course_details' object.id %}" class="form-horizontal" method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|as_crispy_errors }}
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Course Title
                        </div>
                        <div class="col-lg-9">
                            {{ form.title|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Course Thumbnail
                        </div>
                        <div class="col-lg-9">
                            {{ form.thumbnail|as_crispy_field }}
                        </div>
                    </div>
                    {#                    <div class="row mb-lg-3 mt-lg-3">#}
                    {#                        <div class="col">#}
                    {#                            Course Timezone#}
                    {#                        </div>#}
                    {#                        <div class="col-lg-9">#}
                    {#                            {{ form.time_zone|as_crispy_field }}#}
                    {#                        </div>#}
                    {#                    </div>#}

                    {% if user.role.is_admin %}
                        <div class="row mb-lg-3 mt-lg-3">
                            <div class="col">
                                Modify the teacher for the course
                                <p class="text-muted font-weight-light">(option visible only to admin)</p>
                            </div>
                            <div class="col-lg-9">
                                {{ form.user|as_crispy_field }}
                            </div>
                        </div>
                    {% endif %}

                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Course Start Date
                        </div>
                        <div class="col-lg-9">
                            {{ form.start_date|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Course End Date
                        </div>
                        <div class="col-lg-9">
                            {{ form.end_date|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Grading Scheme
                        </div>
                        <div class="col-lg-9">
                            {{ form.grading_scheme|as_crispy_field }}
                            <a type="button" class="btn btn-outline-secondary mt-2"
                               href="{% url 'lms:course_grading_scheme_update' object.id %}">
                                Manage grading scheme
                            </a>
                        </div>
                    </div>
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Course Description
                        </div>
                        <div class="col-lg-9">
                            {{ form.description|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Let students self enroll into the course?
                        </div>
                        <div class="col-lg-9">
                            {{ form.allow_self_enroll|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row mb-lg-3 mt-lg-3">
                        <div class="col">
                            Publish the course?
                        </div>
                        <div class="col-lg-9">
                            {{ form.published|as_crispy_field }}
                        </div>
                    </div>
                </fieldset>
                <div class="pt-5 pb-5">
                    <a class="btn btn-outline-info" href="{% url 'lms:course_details' object.id %}">Discard Changes</a>
                    <button class="btn btn-outline-success" type="submit">Update Course Details</button>
                </div>
            </form>
        </div>
    </div>
{% endblock main-content %}

lms/templates/dashboard/landing/settings/course_grading_scheme_create.html
{% extends 'lms/course/settings/settings_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block main-content %}

    <div class="container">
        <h1 class="text-center pt-3 pb-3 border-bottom">Create Grading Schemes</h1>

        <div class="pb-3">
            <h5 class="pt-3 pb-1 text-muted">Switch to updating an existing Scheme</h5>
            <a type="button" class="btn btn-outline-secondary"
               href="{% url 'lms:course_grading_scheme_update' object.id %}">
                Update existing
            </a>
        </div>


        <div class="pt-3 pb-1">
            <h5>Populate the fields below to generate a new Grading Scheme: </h5>
        </div>

        <form action="{% url 'lms:course_grading_scheme_create' object.id %}" class="form-horizontal" method="POST">
            {% csrf_token %}
            {{ grade_formset.management_form }}

            <fieldset class="form-group">

                {{ scheme_name|crispy }}

                <div class="pt-4">
                    <table class="table table-sm">
                        <caption>Note: Enter complete grade details in each row. Leave blank any additional rows
                        </caption>
                        <thead>
                        <tr>
                            <th scope="col">Grade</th>
                            <th scope="col">Score begin range</th>
                            <th scope="col">Score end range</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for form in grade_formset.forms %}
                            <div>
                                <tr>
                                    {{ form|as_crispy_errors }}
                                    {{ form.id|as_crispy_field }}

                                    {# fixme: remove the labels from the fields #}
                                    <td scope="row" class="fieldWrapper">
                                        {{ form.grade|as_crispy_field }}
                                    </td>
                                    <td scope="row" class="fieldWrapper">
                                        {{ form.score_range_begin|as_crispy_field }}
                                    </td>
                                    <td scope="row" class="fieldWrapper">
                                        {{ form.score_range_end|as_crispy_field }}
                                    </td>
                                </tr>
                            </div>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </fieldset>

            <div class="border-top  pt-3 pb-5">

                <button class="btn btn-outline-success" type="submit">Create Scheme</button>

            </div>
    </div>
    </form>

    </div>
{% endblock main-content %}

lms/templates/dashboard/landing/settings/course_grading_scheme_update_tab.html
{% extends 'lms/course/settings/settings_base.html' %}
{% load crispy_forms_tags %}

{% block main-content %}
    <div class="container">
        <form action="{% url 'lms:course_grading_scheme_update' object.id %}" class="form-horizontal" method="POST">
            {% csrf_token %}

            {{ grade_formset.management_form }}

            <h1 class="text-center">Grading Scheme</h1>
            <fieldset class="form-group">

                <label for="scheme_name">Scheme Name: </label>
                <input type="text" class="form-control" name="scheme_name" id="id_scheme_name"
                       {% if scheme_name.data != None %}value="{{ scheme_name.data }}"{% endif %}
                       required="True">

                <table class="table table-sm">
                    <caption>Grading Scheme</caption>
                    <thead>
                    <tr>
                        <th scope="col">Grade Letter</th>
                        <th scope="col">Score begin range</th>
                        <th scope="col">Score end range</th>
                    </tr>
                    </thead>
                    <tbody>

                    {# Rendering error messages from forms  #}
                    {% for form in grade_formset.forms %}
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}

                        <tr>
                            <th scope="row"><label for="id_form-{{ forloop.counter0 }}-grade"></label>
                                <input type="text" class="form-control"
                                       name="form-{{ forloop.counter0 }}-grade"
                                       id="id_form-{{ forloop.counter0 }}-grade"
                                       {% if form.grade.value != None %}value="{{ form.grade.value }}"{% endif %}>
                            </th>
                            <td><label for="id_form-{{ forloop.counter0 }}-score_range_begin"></label>
                                <input type="number" class="form-control"
                                       name="form-{{ forloop.counter0 }}-score_range_begin"
                                       id="id_form-{{ forloop.counter0 }}-score_range_begin"
                                       {% if form.score_range_begin.value != None %}value="{{ form.score_range_begin.value }}"{% endif %}>
                            </td>
                            <td><label for="id_form-{{ forloop.counter0 }}-score_range_end"></label>
                                <input type="number" class="form-control"
                                       name="form-{{ forloop.counter0 }}-score_range_end"
                                       id="id_form-{{ forloop.counter0 }}-score_range_end"
                                       {% if form.score_range_end.value != None %}value="{{ form.score_range_end.value }}"{% endif %}>
                            </td>
                        </tr>
                    {% endfor %}
                    {#                                        {{ grade_formset }}#}
                    </tbody>
                </table>

            </fieldset>

            <div class="border-top  pt-3 pb-5">
                <button class="btn btn-outline-info" type="submit">Update Grading Scheme</button>
            </div>
        </form>
    </div>
{% endblock main-content %}

lms/templates/dashboard/landing/settings/settings_base.html
{% extends 'lms/lms_base.html' %}

{% block title %}
    Course Settings Page
{% endblock title %}

{% block content %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'course_details' %}active{% endif %}"
               href="{% url 'lms:course_details' object.id %}">
                Course Details
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'course_sections' %}active{% endif %}"
               href="{% url 'lms:course_sections' object.id %}">
                Sections
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'course_manage' %}active{% endif %}"
               href="{% url 'lms:course_manage' object.id %}">
                Manage
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'course_statistics' %}active{% endif %}"
               href="{% url 'lms:course_statistics' object.id %}">
                Statistics
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link
                {% if request.resolver_match.url_name == 'course_grading_scheme_update' %}
                    active
                {% elif request.resolver_match.url_name == 'course_grading_scheme_create' %}
                    active
                {% endif %}"
               href="{% url 'lms:course_grading_scheme_update' object.id %}">
                Manage Grading Schemes
            </a>
        </li>
    </ul>

    {% block main-content %}
        <h1 class="text-center">Course Settings</h1>
    {% endblock main-content %}

{% endblock content %}